services:
  postgres:
    image: postgres:17
    container_name: beershop-postgres
    environment:
      POSTGRES_DB: beershop
      POSTGRES_USER: beershop
      POSTGRES_PASSWORD: beershop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beershop"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: beershop-api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  postgres_data:
